---
apiVersion: v1
kind: Secret
metadata:
  name: stk111-stk111-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/stk111-gateway-gitops
